CREATE TABLE users(
id BIGINT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL
topic_id BIGINT NOT NULL,

PRIMARY KEY(id),
FOREIGN KEY(topic_id) REFERENCES topics(id)
);